services:
  postgres_db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: allan_vargens
      POSTGRES_PASSWORD: allanvargensbrasil
      POSTGRES_DB: Portfolio
    ports:
      - 5432:5432
    volumes:
      - ./back-nest-js/.docker/pgdata:/var/lib/postgresql/data
      - ./back-nest-js/db.sql:/docker-entrypoint-initdb.d/init.sql
