version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-changeme}
      POSTGRES_DB: projects-api
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
       - ./data/script.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
    postgres: